name: placeholder-name # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: placeholder-version # just for humans, typically '1.2+git' or '1.3.2'
summary: placeholder-summary # 79 char long summary
description: |
  placeholder-desc

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  firstapp:
    command: placeholder-name

parts:
  install-binary:
    plugin: dump
    source: src-tauri/target/release/
    source-type: local
    stage:
      - placeholder-name
    prime:
      - placeholder-name
    build-packages: []
    stage-packages:
      - libc6
      - webkit2gtk
